services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5632:5432"
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springpass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: springlab
    restart: always
    user: root
