spring.application.name=spring-lab

spring.datasource.url=jdbc:postgresql://localhost:5632/springlab
spring.datasource.username=springuser
spring.datasource.password=springpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

logging.file.name=logs/spring-lab.log

app.jwt.issuer=spring-lab
app.jwt.secret=0123456789abcdef0123456789abcdef
app.jwt.expires-in-seconds=3600
